function bt_eval(k,q){try{return window.eval.apply(window,[k])}catch(w){q&&q(w)}}var bt_parameter=function(){var k;return function(q,w){var C=w||document;"undefined"===typeof k&&(k=new BrightTag.HTTP.URL(C.location.href));return k.param(q)}}();function bt_meta(k,q){for(var w,C=(q||document).getElementsByTagName("meta"),H=0,J=C.length;H<J;H++)if(w=C[H],w.getAttribute("name")===k)return w.getAttribute("content");return""}
function bt_cookie(k,q){return(new BrightTag.HTTP.Cookie(q||document)).get(k)||""}function bt_data(k,q){var w=BrightTag.V2_RESPONSE?BrightTag.configuredSites()[0]:BrightTag.instance;return w?w.data(k,q):""}window.bt_data_escaped=bt_data;function bt_log(k){window.console&&console.log&&console.log("Yahoo Japan: "+k)}var bt_handle_exception=bt_log;
window.BrightTag=function(k){function q(a,d){return Object.prototype.toString.call(a)==="[object "+d+"]"}function w(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}function C(a){return"\n//at-sourceURL=/BrightTag/"+a.replace(/\s+/g,"_")+".js"}function H(a,d){for(var c=0,b=this.length;c<b;c++)a.call(d,this[c],c,this)}function J(a,d,c){for(var b in a)a.hasOwnProperty(b)&&d.call(c,b,a[b],a)}function r(a,d,c){a&&(O(a)?P.call(a,d,c):m.isObject(a)&&J(a,d,c))}function t(a,d){J(d,function(d,b){a[d]=
b});return a}function O(a){return m.isArray(a)||!m.isString(a)&&a.length}function pa(a){return!!a}function qa(a,d){var c=Array.isArray(this)?this.slice():Array.from(this),b=[];P.call(c,function(c,e){a.call(d,c,e,this)&&b.push(c)});return b}function U(a,d,c){if(a)return ra.call(O(a)?a:[a],d||pa,c)}function sa(a,d){var c=Array.isArray(this)?this.slice():Array.from(this),b=Array(c.length);P.call(c,function(c,e){b[e]=a.call(d,c,e,this)});return b}function A(a,d){var c,b,g=m.isArray(a)?a:[a];c=0;for(b=
g.length;c<b;c++)if(g[c]===d)return!0;return!1}function V(a){return!m.isString(a)?a:a.replace(/%/g,"%25").replace(/#/g,"%23").replace(/&/g,"%26").replace(/'/g,"%27").replace(/;/g,"%3B").replace(/</g,"%3C").replace(/>/g,"%3E")}function W(a){for(var d=5381,c=0,b=a.length;c<b;)d=(d<<5)+d+a.charCodeAt(c++);return d.toString(36)}function Q(a){if("s.yjtag.jp"===a&&"false"!==k.HTTP.Cookie(document).get("testyjproxy"))return"yjtag.yahoo.co.jp"}function X(a){function d(){}function c(a){var b=Array.prototype.slice.call(arguments,
1);x.each(r,function(f){var c=[u].concat(b);(f[a]||d).apply(null,c)})}function b(){D=!0;R=y.length;c("engine:off")}function g(){D&&c("engine:on");D=!1;Y=0;(y[R++]||b)()}function e(a,b){return{type:a,exception:b}}function h(){c("block:finish");g()}function l(b,f){var c=a.createElement(b.tagName),d=x.extend(x.extend({},b.defaults),f||{});x.each(b.supported,function(a){m.isString(a)&&null!=d[a]?c[a]=d[a]:m.isObject(a)&&null!=d[a.option]&&a.setter(c,d[a.option])});return c}function n(b,f){var d=l(t.iframe,
f);d.onerror=function(){c("block:error",e("iframe","Problem loading "+b))};c("block:start",b);d.src=b.toString();a.body.appendChild(d);h()}function f(a,b){var f=l(t.image,b);f.onerror=function(){c("block:error",e("image","Problem loading "+a))};c("block:start",a);f.src=a.toString();h()}function s(b,f,d){var n=!1,s=l(t.script,d);s.onerror=function(){c("block:error",e("script","Problem loading "+b));n||h()};s.onload=s.onreadystatechange=function(){var a;if(!(a=n)){a:{switch(s.readyState){case void 0:case "loaded":case "complete":a=
!0;break a}a=!1}a=!a}a||(n=!0,h())};c("block:start",b);b&&(s.src=b.toString());f&&(s.text=f);f=a.getElementsByTagName("script")[0];f.parentNode.insertBefore(s,f)}function p(a){var b=Array.prototype.slice.call(arguments,1);return function(){a.apply(null,b)}}function K(b){return function(){try{if(c("block:start",b),m.isString(b)){var f=x.trim(b).replace(/^\x3c!--/,"").replace(/--\x3e$/,"");a.defaultView?a.defaultView.eval.call(window,f):a.parentWindow?a.parentWindow.execScript(f):c("block:error",e("wait",
"Could not evaluate wait block ["+f+"]"))}else b()}catch(d){c("block:error",e("wait",d))}finally{h()}}}function v(a){y.push(a);D&&g();return u}function k(a){y.splice(R+Y++,0,a);return u}var u=this,r=[],B={},D=!1,y=[],R=0,Y=0,t={iframe:{tagName:"iframe",defaults:{frameborder:"0",height:"1px",scrolling:"no",width:"1px"},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"frameborder","id","height","scrolling","width"]},image:{tagName:"img",defaults:{},supported:[{option:"display",
setter:function(a,b){a.style.display=b}},"id",{option:"height",setter:function(a,b){a.setAttribute("height",b)}},{option:"width",setter:function(a,b){a.setAttribute("width",b)}}]},script:{tagName:"script",defaults:{type:"text/javascript"},supported:["async","id","type","charset"]}};u.run=function(){c("engine:on");g()};u.options=function(a){x.extend(B,a);return u};u.option=function(a){return B[a]};u.iframe=function(a,b){return v(p(n,a,b))};u.image=function(a,b){return v(p(f,a,b))};u.script=function(a,
b,f){return v(p(s,a,b,f))};u.wait=function(a){return v(K(a))};u.preemptCss=function(a,b){return k(p(s,a,b))};u.preemptIframe=function(a,b){return k(p(s,a,b))};u.preemptImage=function(a,b){return k(p(s,a,b))};u.preemptScript=function(a,b,f){return k(p(s,a,b,f))};u.preemptWait=function(a){return k(K(a))};u.listen=function(a){r.push(a);(a["engine:listen"]||d).apply(null,[u]);return u}}function Z(a){function d(a){e.push(a);l&&!n&&b()}function c(a){a.run()}function b(){var a=e[h];a&&(h++,a.listen(f).run())}
var g,e=[],h=0,l=!1,n=!1,f={"engine:on":function(){n=!0},"engine:off":function(){n=!1;b()}};g=d;this.alwaysQueue=function(){g=d};this.neverQueue=function(){g=c};this.push=function(a){g(a);return a};this.run=function(){l=!0;b()};this.applyListener=function(a){var b,f;b=h;for(f=e.length;b<f;b++)e[b].listen(a)};this.toString=function(){return"Group[name="+a+"; working="+n+"; running="+l+"]"}}function $(a,d){return{"engine:listen":function(c){c.listen(new ta(a,d))}}}function aa(a){function d(a){return g[a]||
(g[a]=new Z(a))}function c(a){return b.addToGroup(a,b.newEngine())}var b=this,g={undefined:new Z(void 0)},e=[];g.undefined.neverQueue();b.addGlobalListener=function(a){e.push(a);r(g,function(b,d){d.applyListener(a)})};b.addToGroup=function(a,b){r(e,function(a){b.listen(a)});return d(a).push(b)};b.newEngine=function(){return new X(a)};b.group=function(a){return c(a)};b.listen=function(){return c().listen.apply(null,arguments)};b.iframe=function(){return c().iframe.apply(null,arguments)};b.image=function(){return c().image.apply(null,
arguments)};b.script=function(){return c().script.apply(null,arguments)};b.wait=function(){return c().wait.apply(null,arguments)};b.run=function(a){d(a).run()};b.alwaysQueue=function(a){d(a).alwaysQueue()};b.neverQueue=function(a){d(a).neverQueue()};b.setOptions=function(){return c()}}function S(a){function d(a){var b,d=a.split(l),c;g={};a=0;for(b=d.length;a<b;a++)(c=h.exec(d[a]))&&(g[c[1]]=unescape(c[2]))}function c(b,f,c){if(b){c=c||{};b=[b+"="+V(f||"")];if((f=c.expires)||0===f)m.isNumber(f)&&(f=
(new Date(f)).toGMTString()),b.push("expires="+f);(f=c.path)&&b.push("path="+f);(f=c.domain)&&b.push("domain="+f);!0===c.secure&&b.push("Secure");!0===c.httponly&&b.push("HttpOnly");c=b.join(";");if(c.length<e)a.cookie=c;else throw{name:"CookieTooLongError",message:"Cookie reached 4096 byte limit"};d(a.cookie)}}function b(a,b){c(a,"",t(b||{},{expires:1}))}var g={},e=4096,h=/([^=]+)=?(.*)/,l=/; ?/;d(a.cookie||"");return{get:function(a){return g[a]},set:c,remove:b,findEach:function(a,b){for(var c in g)g.hasOwnProperty(c)&&
c.match(a)&&b(c,g[c])},clear:function(a){var c=t({},g),d;for(d in c)b(d,a)}}}function ba(a){a=S(a);var d=a.set,c=a.remove;a.set=function(a,c,e){e=t(e||{},{path:"/"});0===e.expires&&(e.expires=+new Date("1/1/2038"));d(a,c,e)};a.remove=function(a,d){c(a,t(d||{},{path:"/"}))};a.purge=function(){};return a}function ca(a,d){function c(a){a=a.expires;return 0!==a&&a<=+new Date}function b(b,c){a.setItem(b,c)}function g(a,b,e){b={value:b,expires:e};c(b)||d.setItem(a,JSON.stringify(b))}function e(a){a=d.getItem(a);
try{return a?JSON.parse(a):void 0}catch(b){}}function h(a){a=e(a);var b;return a&&(a.hasOwnProperty("value")&&a.hasOwnProperty("expires"))&&!c(a)?(b=a.value,delete a.value,[b,a]):[]}function l(a,b,c,d){for(var e,l=0,g=a.length;l<g;l++)e=a.key(l),!c[e]&&(c[e]=e.match(b))&&d(e)}return{set:function(a,c,d){a&&null!=c&&(d=d||{},(null!=d.expires?g:b)(a,c,d.expires))},get:function(b){return a.getItem(b)||h(b)[0]},findEach:function(b,c){var e={};l(a,b,e,function(b){var d=a.getItem(b);null!=d&&c(b,d)});l(d,
b,e,function(a){var b=h(a),d=b[0],b=b[1];null!=d&&c(a,d,b)})},remove:function(b){a.removeItem(b);d.removeItem(b)},purge:function(){for(var a,b,l=d.length;l--;)a=d.key(l),(b=e(a))&&(b.hasOwnProperty("value")&&b.hasOwnProperty("expires"))&&c(b)&&d.removeItem(a)}}}function L(a,d){var c={};c.set=a.set;c.findEach=function(b,c){var e={};a.findEach(b,function(a,b,d){e[a]=!0;c(a,b,d)});d.findEach(b,function(b,d,n){e[b]||(a.set(b,d,n),c(b,d,n))})};c.get=function(b){var c=a.get(b);void 0===c&&(c=d.get(b),void 0!==
c&&a.set(b,c));return c};c.remove=function(b){a.remove(b);d.remove(b)};c.purge=function(){a.purge();d.purge()};return c}function M(a){function d(a){var b={};if(!m.isString(a))return a;r(a.split("&"),function(a){if(""!==a){var c=a.split("=");a=decodeURIComponent(c[0]);c=c[1]&&decodeURIComponent(c[1].replace(/\+/g," "));(null==b[a]?b[a]=[]:b[a]).push(c)}});return b}function c(a,b){var c=[];r(a,function(a){if(m.isObject(a))return!1;a=null==a||""===a?b:a;(m.isString(a)||m.isNumber(a)||m.isBoolean(a))&&
c.push(a)});return c}function b(a){return!m.isArray(a)?[a]:a}function g(a,b){var c=encodeURIComponent(a),d=encodeURIComponent(b);return c+"="+d}var e=this,h={};t(h,d(a));e.param=function(a){a=h[a]||[""];return 1<a.length?a:a[0]};e.params=function(){return h};e.appendParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(h[a]=(null==h[a]?h[a]=[]:h[a]).concat(e))}return this};e.replaceParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(h[a]=(h[a]=[]).concat(e))}return this};e.appendParams=function(a){r(a,
e.appendParam);return this};e.alwaysAppendParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(h[a]=(null==h[a]?h[a]=[]:h[a]).concat(e))}return this};e.alwaysReplaceParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(h[a]=(h[a]=[]).concat(e))}return this};e.alwaysAppendParams=function(a){r(a,e.alwaysAppendParam);return this};e.appendPartialQueryString=function(a){a&&e.alwaysAppendParams(d(a));return this};e.deleteParam=function(a){delete h[a]};e.toString=function(){var a=[];r(h,function(b,
c){r(c,function(c){a.push(g(b,c))})});return a.join("&")}}function E(a){function d(){var a=k.toString();return h+l+(0<a.length?"?"+a:"")}var c={},b,g,e,h,l,n,f,s,p,k,v=a.match(ua);a=v[1]||"";g=v[2]||"";e=(v[3]||"").substring(1);b=g+(e?":"+e:"");h=a+(b?"//"+b:"");l=v[4]||"";n=(f=l.match(/^(.+?)?\/([^\/]+)?$/))&&f[1]||"";f=f&&f[2]||"";s=(v[5]||"").substring(1);p=(v[6]||"").substring(1);k=new M(s);t(c,k);t(c,{origin:h,scheme:a,host:b,hostname:g,port:e,path:l,pathname:n,scriptname:f,queryString:k.toString,
fragment:function(){return p},tooLong:function(){return 2082<d().length},asString:d});c.toString=d;return c}function da(a,d,c){function b(){var b=c.createEvent("Event");b.initEvent(d,!0,!1);try{b.currentTarget=b.target=a}catch(e){bt_log("warning: can not set target for ["+d+"] event: "+e)}return b}function g(){var a=c.createEventObject("Event");a.type=d;a.cancelable=!0;a.bubbleable=!1;return a}function e(c){setTimeout(function(){try{(c.handleEvent||c).call(a,h?b():g())}catch(e){bt_log("error: overriding ["+
d+"] event: "+e)}},0)}var h=!!a.addEventListener,l=h?"addEventListener":"attachEvent",n=a[l];a[l]=function(b,c,g){if(c&&("function"==typeof c||"function"==typeof c.handleEvent))if(b==d||b=="on"+d)e(c);else try{h?n.call(a,b,c,g):n(b,c)}catch(l){bt_log("error: proxying ["+b+"] event: "+l)}}}function ea(a,d,c){function b(a){a.hasOwnProperty("enabled")&&(s=a.enabled);a.hasOwnProperty("timestamp")&&(k=a.timestamp,s=!0);a.hasOwnProperty("site")&&(n=a.site);a.hasOwnProperty("referrer")&&(f=a.referrer)}function g(c){c&&
b(c);p=[];a.remove(d)}function e(){try{return JSON.stringify({site:n,referrer:f,errors:p})}catch(a){bt_log("problem serializing errors: "+a.message)}return null}function h(a){var b=m.isObject(a)?t({},a):{};b.type=b.type||"unknown";b.message=b.message||a.toString();b.timestamp=k;return b}function l(){g();p.push(h({type:"runtime",message:"Too many errors"}));a.set(d,e())}if(!a)throw Error("ErrorManager requires a store");var n,f,s=!0,p=[],k=+new Date;c&&b(c);return{configure:b,reset:g,hasErrors:function(){return 0<
p.length},tooManyErrors:l,processStoredErrors:function(){var b=a.get(d);if(b)try{var c=JSON.parse(b)||{};n=c.site;f=c.referrer;m.isArray(c.errors)&&(p=p.concat(c.errors))}catch(e){bt_log("problem reading stored errors: "+e.message)}},push:function(b){bt_log("error: "+JSON.stringify(b));if(s&&b&&!(-1>b.tagId||-1>b.pageId))try{p.push(h(b)),a.set(d,e())}catch(c){if("CookieTooLongError"!=c.name)throw c;l()}},toJSON:e,toArray:function(){return p}}}function fa(a,d){return new function(a,b){function d(a){f.wait(a)}
function e(a){function b(){n=k.jQuery;d(a)}l="var $ = BrightTag.$; ";k.jQuery?b():f.script(k.instance.baseUri()+"BrightTag.jquery-1.5.1.js").wait(b)}var h={},l="",n,f=k.Blab.group(b);h.getJQuery=function(){return n};h.ensureJQuery=function(f){h.ensureJQuery=d;n=a.jQuery;(n?d:e)(f);k.Blab.run(b)};h.functionWithAccess=function(a,b){return new Function(a,l+b)};return h}(a,d)}function ga(a){function d(a,c){c&&c.findEach(a,function(a,c){b.appendParam(a,c)})}function c(a,b){return function(c){bt_log("invalid "+
a+" expression: "+b+", exception = "+c)}}var b=this,g=a.window,e=a.parentReferrer,h=a.referrer,l=E(0===a.host.length?"":(/^[a-z0-9+.-]+:\/\/.+/.test(a.host)?"":"//")+a.host+"/tag"),n=a.store?a.store.get("X-BT-InspectSession"):null;t(b,l);b.toString=l.toString;b.appendParams({site:a.site,referrer:h,docReferrer:a.docReferrer,mode:a.mode,H:W(h||a.document.location.href)});n&&b.appendParam("inspect-session",n);h!==e&&b.appendParam("parentReferrer",e);d(/^btps\..+/,new S(a.document));d(/^btpdb\..+/,a.store);
b.appendData=function(a){var c=bt_data(a),c=m.isArray(c)||m.isObject(c)?g.JSON.stringify(c):c;return b.alwaysReplaceParam("_cb_"+("bt_data('"+a+"')"),c)};b.appendJs=function(a){var d=c("client binding expression",a);return b.alwaysReplaceParam("_cb_"+a,z(a,d))};b.cf=function(a){m.isArray(a)||(a=[a]);var c=b.param("cf");c&&(a=Array(c).concat(a));b.replaceParam("cf",a.join());return b};b.addCf=function(a,d){if(!z(d,c("conditional fire",d,"tags/"+a+"-cf.js")))return!1;var e=b.param("cf");b.replaceParam("cf",
e?e+","+a:a);return!0};b.length=function(){return b.toString().length};b.isTooLarge=function(){return 2028<b.length()};var f=b.toString();b.hasConditions=function(){return f!=b.toString()}}function ha(a,d){function c(a,b){r(b,function(b,c){a[a.type+"."+b]=c});d.push(a)}function b(a,b,c){var d=k.instance.serverURL();r(a,function(a){a.trigger(b,c,d)});d.hasConditions()&&(d.appendParam("mode","v1"),k.Blab.script(d.asString()))}function g(a,d,e){function f(b,d){r(h,function(f){var g,h=f.name;try{g=k[f.dbe];
if(!g){var l=k,p=f.dbe,v,m=f.dbe,u=C("event-dbes/"+h+"-page-"+(B||"adhoc")+"-event-"+a);v=n.functionWithAccess(["eventObject","eventData"],"return "+m+";"+u);g=l[p]=v}e.data(h,g.call(b.target,b,d))}catch(r){c({type:"evdbe",message:r.toString(),pageId:B||-1},{name:h,eventName:a})}})}var g={},h=[],k={},B=(d||{}).pageId;g.data=function(a,b){h.push({name:a,dbe:b});return g};g.applyDataBindings=f;g.handler=function(c){var d,e=l[a];e&&0<e.length&&(d=Array.prototype.slice.call(arguments,1),f(c,d),b(e,c,
d))};return g}function e(a){function b(a){0<l.length&&(a.cf(l),r(k,function(b){a.appendData(b)}),r(y,function(b){a.appendJs(b)}))}function d(a,b){return function(c){bt_log("Invalid "+a+" expression: "+b+", exception = "+c)}}var e={},f={},g,h,l=[],k=[],y=[];e.execute=function(b,d){t(f,d||{});if(m.isFunction(b))h=b;else if(m.isString(b))a:{try{var g=C("events/"+a+"-tag-"+(f.tagId||"adhoc"));h=n.functionWithAccess(["eventObject","eventData"],b+g);break a}catch(l){c({type:"evparse",message:l.toString(),
tagId:f.tagId||-1},{eventName:a})}h=void 0}else bt_log("when.execute: unknown action: "+b);return e};e.evaluate=function(a){g=a;return e};e.fire=function(a){l.push(a);return e};e.appendData=function(a){k.push(a);return e};e.appendJs=function(a){y.push(a);return e};e.trigger=function(e,l,n){var k=d("post-event conditional fire",g);if(!g||z(g,k)){try{h&&h.call(e.target,e,l)}catch(y){c({type:"evwait",message:y.toString(),tagId:f.tagId||-1},{eventName:a})}b(n)}};return e}var h={},l={},n=fa(a,"BrightTag.jQuery"),
f=/^direct\//i;h.executeActions=b;h.Binder=g;h.bind=function(a,b,c,d){var e=g(a,d,k.instance);n.ensureJQuery(function(){var a=n.getJQuery(),d=a(b);if(m.isString(b)&&!f.test(c)&&(d.on||d.live))if(d.on)a(document).on(c,b,e.handler);else d.live(c,e.handler);else d.bind(c.split(f).pop(),e.handler)});return e};h.EventAction=e;h.when=function(a){var b=e(a),c=l[a];c||(c=l[a]=[]);c.push(b);return b};return h}function va(a,d,c,b){function g(b,d,e){var g=a.group(e).options(d||{});g.wait(function(){c.process(g,
b)})}var e=!1,h={};h[b]=!0;return{tag:function(c,d){var f;f=d&&d.group;f=!e&&!f?b:f;g(c,d,f);f&&void 0===h[f]&&(h[f]=!0,e&&a.run(f))},run:function(){a.addGlobalListener($(d,c));e=!0;r(h,a.run)}}}function ia(a,d){function c(a){r(m.isArray(a)?a:[a],function(a){m.isFunction(a)?a():p.write('<script type="text/javascript" src="'+a+'">\x3c/script>')})}function b(a){var b=v.group().options({tagId:-2});r(m.isArray(a)?a:[a],function(a){(m.isFunction(a)?b.wait:b.script)(a)})}function g(a){p.write(a)}function e(a,
b){B.tag(a,b)}function h(a){f.writeScript=a?c:b;f.appendContent=a?g:e}function l(a){r(a,function(a){if(a.name){var b=t({},a);delete b.name;delete b.value;u.set(a.name,a.value,b)}})}function n(b){q.hasErrors()&&(b.appendParam("errors",q.toJSON()),b.tooLong()&&(b.deleteParam("errors"),q.tooManyErrors(),b.appendParam("errors",q.toJSON())));q.reset({site:a.site,referrer:a.referrer||p.location.href})}var f=this,s=a.data||{},p=a.document||{},K=a.window||{},v=a.blab||k.Blab,q=a.errorManager,u=a.store,w=
ja(p),B=a.asyncTagManager||va(v,p,w,"domready"),D=fa(window,"jquery");f.referrer=a.referrer;f.parentReferrer=a.parentReferrer;f.docReferrer=a.docReferrer;f.site=a.site;f.host=a.host;f.loadOnly=!!a.loadOnly;q&&v.addGlobalListener(new ka(q));v.run("serializer");f.load=function(){var a=Array.prototype.slice.call(arguments,0);r(a,function(a){m.isFunction(a)?v.addToGroup("serializer",v.newEngine().wait(function(){a(f)})):m.isObject(a)&&a.src?f.library(a.src,a.options):m.isString(a)&&f.library(a)})};f.library=
function(a,b){v.addToGroup("serializer",v.newEngine().options(b||{}).script(a))};h(A(a.mode,"sync"));f.domReady=function(){A(a.mode,"sync")&&h(!1);B.run()};f.parameter=function(a){return window.bt_parameter(a,p)};f.meta=function(a){return window.bt_meta(a,p)};f.cookie=function(a){return window.bt_cookie(a,p)};f.data=function(a,b){if(void 0!==b)return s[a]=b;b=s[a];return null==b?"":b};f.dbe=function(a,b,c){function d(b){q&&q.push({type:"dbe",message:b.toString(),"dbe.name":a,pageId:(c||{}).pageId||
-1})}null==s[a]&&f.data(a,z(b,d,"page-dbes/"+a+"-page-"+(c&&c.pageId||"adhoc")))};f.errors=function(a){k.V2_RESPONSE=!1;q.configure(a)};f.store=u?l:function(){};f.serverURL=function(){return new ga(a)};f.defaultBaseUri=function(){return("https:"==p.location.protocol?"https:":"http:")+"//static-s.tgm.yahoo-net.jp/"};f.baseUri=function(){var a=/\btag(\.[^.]+|-n)?\.js(#.*)?$/;return d&&d.src&&d.src.replace(a,"")||f.defaultBaseUri()};f.primary=function(){function a(){var b=f.serverURL();q&&(q.processStoredErrors(),
n(b));return b.toString()}var b=[];K.JSON?b.push(a()):(b.push(f.baseUri()+"json2.js"),b.push(function(){f.writeScript(a())}));f.writeScript(b)};f.secondary=function(a){var b=f.serverURL(),c=b.toString();a(b);b.toString()!=c&&(b.appendParam("mode","v1"),q&&n(b),b.isTooLarge()?f.post(b):f.writeScript(b.toString()))};f.post=function(a){D.ensureJQuery(function(){D.getJQuery().ajax({url:"https://"+a.host+a.path,type:"POST",dataType:"text",success:bt_eval,data:a.queryString(),xhrFields:{withCredentials:!0}})})}}
function F(){var a={},d={};return{on:function(c,b){var d=a[c];d||(d=a[c]=[]);d.push(b)},once:function(a,b){var g=d[a];g||(g=d[a]=[]);g.push(b)},emit:function(c){function b(a){a.apply(this,g)}var g=Array.prototype.slice.call(arguments,1);r(a[c],b);r(d[c],b);d[c]=[]}}}function wa(a){function d(a){return null!=g[a]}function c(a,b){void 0!==b&&(g[a]=b);var c=g[a];return null==c?"":c}var b,g=t({},a);return b=t({dbe:function(a,g,l){if(!d(a)&&(g=z(g,function(c){b.emit("error",c,a,l)}),null!=g))return c(a,
g)},data:c,hasData:d},F())}function xa(a){var d,c={},b=["eventObject","eventData","$","bt_data"];return d=t({dbe:function(a,e){try{c[a]=new Function(b,"return "+e+";")}catch(h){h.type="evdbe",d.emit("error",h,a)}return d},trigger:function(b,e,h){var l=b.target,n=[b,e,h,a.data];r(c,function(b,c){try{a.data(b,c.apply(l,n))}catch(e){e.type="evdbe",d.emit("error",e,b)}})}},F())}function ya(a){function d(a){g.push(a);return b}function c(a){try{return new Function(h,a)}catch(c){c.type="evparse",b.emit("error",
c)}}var b,g=[],e=function(){return!0},h=["eventObject","eventData","$","bt_data"];return b=t({fire:function(a){return d(function(b){b.fire(a)})},appendData:function(a){return d(function(b){b.appendData(a)})},appendJs:function(a){return d(function(b){b.appendJs(a)})},execute:function(e){function g(c,d,e,h){try{f.call(d.target,d,e,h,a.data)}catch(l){l.type="evwait",b.emit("error",l)}}var f=m.isString(e)?c(e):e;return f?d(g):b},evaluate:function(d){var g=c("return "+d);e=g?function(b,c,d,e){return g.call(c.target,
c,d,e,a.data)}:function(){return!1};return b},trigger:function(a,b,c,d){e(a,b,c,d)&&r(g,function(e){e(a,b,c,d)})}},F())}function za(a){var d=/^direct\//i,c=!1;return{bind:function(a,c,e){function h(a){var b=Array.prototype.slice.call(arguments,1);e(a,b,k.jQuery||window.jQuery)}var l=k.jQuery||window.jQuery,n=l(a),f=!m.isString(a)||d.test(c);if(!f&&n.on)l(document).on(c,a,h);else!f&&n.live?n.live(c,h):n.bind(c.split(d).pop(),h)},newBinder:function(a){return xa(a)},newHandler:function(a){return ya(a)},
ensureLibrary:function(b){k.jQuery||window.jQuery?b():(c||(c=!0,a.run()),a.wait(b))}}}function Aa(a,d){function c(b,c,d,k){var f=T(a);r(b,function(a){a.trigger(f,c,d,k)});g.emit("triggered",f)}var b={},g=F();return t(g,{bind:function(e,h,l,k){function f(a,d,f){s.trigger(a,d,f);c(b[e],a,d,f)}var s=d.newBinder(a,e);s.on("error",function(a,b){g.emit("error",a,{name:b,eventName:e},k)});d.ensureLibrary(function(){try{d.bind(h,l,f)}catch(a){g.emit("error",a,{eventName:e},k)}});return s},handle:function(c,
h){var l=d.newHandler(a);l.on("error",function(a){g.emit("error",a,{eventName:c},h)});b[c]=b[c]||[];b[c].push(l);return l}})}function ja(a){function d(a,b){a.src?b.preemptScript(a.src,a.innerHTML):a.innerHTML&&b.preemptWait(a.innerHTML)}function c(a,b){for(var h=a.childNodes||[],l=0,k=h.length;l<k;l++){var f=h[l];"SCRIPT"==f.tagName?d(f,b):c(f,b)}}var b=a.createElement("div");return{process:function(g,e){if(0!==e.length){b.innerHTML="<br/>"+e;for(var h=b.childNodes||[],l=1,k=h.length;l<k;l++){var f=
h[l];if("SCRIPT"==f.tagName)d(f,g);else{try{a.body.appendChild(f.cloneNode(!0))}catch(s){bt_log("error appending content to body: "+s)}c(f,g)}}}}}}function Ba(a){function d(b){a.write(b);return c}var c={tag:d,script:function(a){return d('<script type="text/javascript" src="'+a+'">\x3c/script>')},wait:function(a){a();return c}};return c}function Ca(a,d){function c(c,d){var g=c&&c.group;d(a.group(g).options(c||{}));g&&void 0===b[g]&&(b[g]=!0,a.run(g))}var b={},g={tag:function(a,b){c(b,function(b){b.wait(function(){d.process(b,
a)})});return g},script:a.script,wait:a.wait};return g}function Da(a,d){var c=d;return{tag:function(a,d){return c.tag(a,d)},script:function(a){return c.script(a)},wait:function(a){return c.wait(a)},sync:function(){c=a},async:function(){c=d}}}function ka(a){return{dbe:function(d,c,b){a.push({type:"dbe",message:d.toString(),"dbe.name":c,pageId:(b||{}).pageId||-1})},events:function(d,c,b){var g=d.type,e="evdbe"===g?"pageId":"tagId",h={type:g,message:d.toString()};r(c,function(a,b){h[g+"."+a]=b});h[e]=
(b||{})[e]||-1;a.push(h)},"block:error":function(d,c){var b,g,e;c&&(b=c.type,g=c.exception||c,e=d.option("tagId")||-1,a.push({type:b,message:g.toString(),tagId:e}))}}}function Ea(a,d){function c(){var b=new E(a.src),c={},h=b.fragment(),l=Q(b.host);c.staticHost=b.host+b.pathname;l&&(c.host=l);b=(new M(h||"")).params();r(b,function(a,b){c[a]=1<b.length?b:b[0]});void 0===b.referrer&&void 0!==d.location.href&&(c.referrer=d.location.href.split("#")[0]);return c}function b(){var b=w(a.innerHTML);return 0===
b.length?{}:z("(\n"+b+"\n)",function(a){bt_log("json configuration error: "+a)})}return{isTagjs:function(){return/\/tag(\.[^.]+|-n)?\.js(\?.*)?(#.*)?$/.test(a.src)},toJSON:function(){return t(c(),b())},script:a}}function Fa(a){return{isTagjs:function(){return!0},toJSON:function(){return a||{}},script:{src:void 0}}}function la(){function a(){return d}var d;return d={fire:a,appendData:a,appendJs:a,execute:a,when:a}}function T(a){function d(a,b){for(var c in a)if(b(c,a[c]))return!0;return!1}var c,b=
[],g={};return c={toJSON:function(){var a=0<b.length?{cf:b.join()}:{};return t(a,g)},fire:function(a){m.isArray(a)||(a=[a]);a=U(a,function(a){return null!=a&&""!==a});b=b.concat(a);return c},appendData:function(b){var d=a.data(b);g["_cb_bt_data('"+b+"')"]=m.isArray(d)||m.isObject(d)?JSON.stringify(d):d;return c},appendJs:function(a){g["_cb_"+a]=z(a);return c},execute:function(a){a();return c},when:function(b){var d;try{return d=new Function(["bt_data"],"return "+k.trim(b)),d(a.data)?c:la()}catch(g){bt_log("conditional evaluation error: ["+
g.toString()+"] while evaluating ["+b+"]")}return la()},hasConditions:function(){return 0<b.length||d(g,function(a,b){return null!=b})}}}function Ga(a,d,c,b,g,e){function h(){u=!0;d.async();m.mode=x.filter(m.mode,function(a){return"sync"!==a})}function l(a){if(null==a||a.hasConditions())b.reset({site:m.site,referrer:m.referrer||window.location.href})}function n(a){var c=E("//"+q+"/tag").appendParams({site:m.site,mode:m.mode,H:m.H,referrer:m.referrer,docReferrer:m.docReferrer}).appendParam("mode",
"v2").alwaysAppendParams(a);(a=I.get("X-BT-InspectSession"))&&c.appendParam("inspect-session",a);g.findEach(RegExp("^btp(s|db)\\."+m.site+"\\..+"),function(a,b){c.appendParam(a,b)});return c.appendParams({errors:b.hasErrors()?b.toJSON():null})}function f(a){if(null==a)return n();if(a.hasConditions())return n(a.toJSON())}function s(a){var b=f(a);b?(l(a),b.tooLong()?t.ensure("jQuery",function(){k.jQuery.ajax({url:"https:"+(b.host?"//"+b.host:"")+b.path,type:"POST",data:b.queryString(),xhrFields:{withCredentials:!0}})}):
d.script(b.toString())):l(a)}var p,m=x.extend({},e),q=m.host||"",r=F(),u=!1,t=new Ha(d,m);c.on("triggered",s);return p=x.extend({config:m,diagnostic:function(a){a&&(m.diagnostic=a,p.emit("diagnostic",a))},errors:function(a){b.configure({timestamp:a})},dbe:function(b,c,d){var e=a.dbe(b,c,d);null!=e&&p.emit("dbe",b,c,e,d)},data:a.data,dataref:function(a){return null==a?"":'BrightTag.site("'+m.site+'").data("'+a.replace(/"/g,"\\x22")+'")'},store:function(a){x.each(a,function(a){if(a.name){var b=x.extend({},
a);delete b.name;delete b.value;g.set(a.name,a.value,b)}})},tag:function(a,b){p.emit("tag",a,b);return d.tag(a,b)},script:d.script,wait:d.wait,events:{bind:function(a,b,d,e){p.emit("event-binding",a,b,d,e);return c.bind(a,b,d,e)},on:c.handle},when:function(b,c){T(a).when(b).execute(function(){c(p)});return p},domready:function(a){if(null==a)h();else r.once("domready",a);u&&r.emit("domready",p)},primary:function(){t.ensure("JSON",function(){b.processStoredErrors();s()})},secondary:function(b){var c=
T(a);b(c);s(c)}},F())}function Ia(a){a=E(a.staticHost+"/BrightTag.jquery-1.5.1.js");return za((new X(document)).script(a))}function Ja(a,d,c){var b=Ba(document);a=Ca(a,d);b=Da(b,a);x.contains(c.mode,"sync")&&b.sync();return b}function Ka(a){var d,c,b,g,e,h,l,n;if((l=a.site)&&!N[l])return d=wa(a.data),c=new aa(document),n=ja(document),b=Ja(c,n,a),e=Aa(d,Ia(a)),h=ea(G?L(G,I):I,"__bterr_"+l,{site:l,referrer:a.referrer,enabled:!1}),g=ka(h),d.on("error",g.dbe),e.on("error",g.events),c.addGlobalListener(g),
k.Events.onDOMReady(function(){c.addGlobalListener($(document,n))}),a=N[l]=Ga(d,b,e,h,G?L(I,G):I,a)}function ma(a,d,c){try{var b,g,e=a.toJSON();if(!(k.instance&&k.instance.site===e.site)){var h=e.referrer||d.location.href,l=t({host:"s.tgm.yahoo-net.jp",staticHost:"static-s.tgm.yahoo-net.jp",H:W(h),referrer:h.split("#")[0],docReferrer:d.document.referrer},e);b=Ka(l);if(e.site&&!k.instance&&!na&&!A(e.mode,"v2")&&!A(e.mode,"v2b")){var n=a.script,f=oa();k.EventBinding=ha(f.window,f.errorManager);k.instance=
new ia(t(f,e),n);g=k.instance;b.config.loadOnly=!0}else if(b){var m=b.config,p;var q=b.config.mode;p=A(q,"v2")?q:!q?"v2":["v2"].concat(q);m.mode=p}c&&c(b,g);return b}}catch(r){bt_log("error configuring site ["+a.script.src+"]: "+r)}}function La(a){var d,c,b=[];if(m.isArray(a))b=a.slice(0);else{d=0;for(c=a.length;d<c;d++)b.push(a[d])}return b}function Ma(a){if(!na&&!A(a.config.mode,"v2")&&!A(a.config.mode,"v2b"))k.Events.onDOMReady(function(d){a.domready()});else a.config.loadOnly||(k.Events.onDOMReady(function(d){a.domready()}),
a.primary())}function oa(){var a,d=ba(document),c=d,b=d;try{window.localStorage&&window.sessionStorage&&(a=ca(sessionStorage,localStorage),a.purge(),c=L(d,a),b=L(a,d))}catch(g){bt_log("Unable to access DOM storage: "+g)}return{id:Math.random(),loadOnly:!1,window:window,document:document,host:"s.tgm.yahoo-net.jp",parentReferrer:top!=self&&self.window?self.window.location.href:null,docReferrer:document.referrer,data:{},store:c,errorManager:ea(b,"__bterr")}}if(k)return k;var na=!1;k={};var m={isString:function(a){return q(a,
"String")},isArray:function(a){return q(a,"Array")},isNumber:function(a){return q(a,"Number")},isBoolean:function(a){return q(a,"Boolean")},isFunction:function(a){return q(a,"Function")},isObject:function(a){return null===a||void 0===a?!1:q(a,"Object")}},z=bt_eval,P=Array.prototype.forEach?Array.prototype.forEach:H,ra=Array.prototype.filter?Array.prototype.filter:qa,Na=Array.prototype.map?Array.prototype.map:sa,x={contains:A,each:r,extend:t,filter:U,map:function(a,d,c){if(a)return Na.call(O(a)?a:
[a],d,c)},trim:w,getTagserveHostOverride:Q},ta=function(){function a(){}function d(a,b,c){try{a[b]=c}catch(d){bt_log("warning: could not assign value to 'document."+b+"': "+d)}}var c,b=[],g=function(a){c.push(a)};return function(e,h){var l;this["block:start"]=function(){b.push([c,e.write,e.writeln,e.open,e.close]);c=[];d(e,"write",g);d(e,"writeln",g);d(e,"open",a);d(e,"close",a)};this["block:finish"]=function(){try{h.process(l,c.join(""))}finally{var a=b.pop();c=a[0];d(e,"write",a[1]);d(e,"writeln",
a[2]);d(e,"open",a[3]);d(e,"close",a[4])}};this["engine:listen"]=function(a){l=a}}}(),ua=/^(?:([^:\/]+:)?\/\/)?([^:\/?#]+)?(:[0-9]+)?([^?#]*)(\?[^#]*)?(#.*)?$/,Ha=function(){function a(a,b){this.tagMgrRouter=a;this.config=b}var d={JSON:{object:"JSON",path:"/json2.js"},jQuery:{object:"BrightTag.jQuery",path:"/BrightTag.jquery-1.5.1.js"}};a.prototype={ensure:function(a,b){var g=d[a];if(g){var e=g.object.split("."),h=window,l=e.length-1,k,f;for(f=0;f<l;f++){k=e[f];h=h[k];if(!h)throw"DependencyManager: Could not find key "+
k;h=h[e[f]]}h?b():this.tagMgrRouter.script(E(this.config.staticHost+g.path)).wait(b)}}};return a}(),N={},G,I=ba(document);try{window.localStorage&&window.sessionStorage&&(G=ca(sessionStorage,localStorage),G.purge())}catch(Oa){bt_log("Unable to access DOM storage: "+Oa)}k.Escaper={cookie:V,javascript:function(a){return!m.isString(a)?a:a.replace(/\\/g,"\\\\").replace(/'/g,"\\x27").replace(/"/g,"\\x22").replace(/\n/g,"\\n").replace(/\r/g,"\\r")}};k.Random={integer:function(a){return Math.floor(Math.random()*
(a||1E8))}};k.pushIfDefined=function(a,d,c){a&&(a.constructor==Array&&null!=d)&&a.push(c||d)};k.ServerURL=ga;k.Main=function(a){function d(b){(b=b.fragment())&&r((new M(b)).params(),function(b,c){a[b]=c[0]})}function c(b){function c(a){bt_log("configuration error: "+a)}b=w(b);0!==b.length&&t(a,z("(\n"+b+"\n)",c,"site-config"))}var b,g,e=function(){var b,c,d=/\/tag(\.[^.]+|-n)?\.js(#.*)?$/,e=a.document.getElementsByTagName("script");for(b=e.length-1;-1<b;b--)if(c=e[b],d.test(c.src))return c}();e&&
(g=new E(e.src),a.host=a.host||Q(g.host),d(g),c(e.innerHTML));if(null!=a.site){k.Events.enablePageReadyOverrides();try{b=new ia(a,e),k.Events.onDOMReady(b.domReady),b.loadOnly||b.primary()}catch(h){bt_log("execution error: "+h)}return b}};k.CookieSync={pushImage:function(a){(new Image).src=a;throw"CookieSync.pushImage no longer supported ["+a+"]";},pushIframe:function(a){throw"CookieSync.pushIframe no longer supported ["+a+"]";}};k.EventBindingManager=ha;k.defaultConfig=oa;k.eval=z;k.Types=m;k.trim=
x.trim;k.Util=x;k.each=x.each;k.extend=x.extend;k.HTTP={Cookie:S,QueryString:M,URL:E};k.Blab=new aa(document);k.Events=new function(a,d){function c(){}function b(a,b,c){a[r](u+b,c,!1)}function g(a,b,c){a[t](u+b,c,!1)}function e(){var a=d.readyState;if("loading"==a)return!1;if("complete"==a)return!0;a:{try{w("left")}catch(b){a=!1;break a}a=!0}return a}function h(a,b,c){var d=this;setTimeout(function(){a()?b.call(d):h(a,b,c)},c)}function k(){k=c;m&&da(d,p,d)}function n(){k();da(a,q,d)}var f=this,m=
!!a.addEventListener,p="DOMContentLoaded",q="load",r=m?"addEventListener":"attachEvent",t=m?"removeEventListener":"detachEvent",u=m?"":"on",w=d.documentElement.doScroll||function(){throw"No doScroll";};f.listen=b;f.unlisten=g;f.onDOMReady=function(c){e()?c.call(this):d.addEventListener?(b(d,p,c),b(d,p,function(){g(a,q,c)}),b(a,q,c)):h(e,c,1)};f.enablePageReadyOverrides=function(){f.enablePageReadyOverrides=c;e()?n():(m&&b(d,p,k),b(a,q,n))}}(window,document);k.Events.enablePageReadyOverrides();k.Content=
new function(a){a=a||k.Blab;return{iframe:a.iframe,image:a.image,link:a.link,script:a.script}}(k.Blab);k.V2_RESPONSE=!0;k.site=function(a,d){try{var c=N[a];c&&d&&d(c);return c}catch(b){bt_log("error while executing site configuration ["+a+"]: "+b)}};k.configureNewSites=function(a,d){r(La(a.document.getElementsByTagName("script")),function(c){c=Ea(c,a);c.isTagjs()&&ma(c,a,d)})};k.configureSite=function(a,d,c){return ma(Fa(a),d,c)};k.configuredSites=function(){var a=[];x.each(N,function(d,c){a.push(c)});
return a};k.initializeSite=function(a,d){d&&(k.Events.onDOMReady(d.domReady),d.loadOnly||d.primary());a&&Ma(a)};return k}(window.BrightTag);(function(k){k.configureNewSites(window,k.initializeSite);null==k.instance&&setTimeout(function(){null==k.instance&&k.configureNewSites(window,k.initializeSite)},0)})(BrightTag);var _bt_url_prefix,_bt_referrer,_bt_site,_bt_mode;
function btServe(k){var q=BrightTag,w={referrer:_bt_referrer,site:_bt_site,mode:_bt_mode};null!=_bt_url_prefix&&(w.host=_bt_url_prefix);q.configureSite(q.extend(w,k),window,q.initializeSite)};
